/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/nordic/scenario/Ambiente.glb --transform 
Files: public/models/nordic/scenario/Ambiente.glb [33.56MB] > C:\Users\Pietro Goffredo\configuratore-portoni\Ambiente-transformed.glb [5.95MB] (82%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Ambiente-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.684, -0.449, 4.153]} scale={0.396}>
        <mesh geometry={nodes.evergreen_short_3004.geometry} material={materials['Pine_Bark.001']} />
        <mesh geometry={nodes.evergreen_short_3004_1.geometry} material={materials['Evergreen_Leaf_1.001']} />
      </group>
      <group position={[2.172, -0.046, 3.072]} rotation={[0, 1.275, 0]} scale={0.955}>
        <mesh geometry={nodes.tree003.geometry} material={materials['pine procedural.002']} />
        <mesh geometry={nodes.tree003_1.geometry} material={materials['Material.006']} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials.mPlaster} position={[1.7, 6.5, -4.934]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.mMetal} position={[3.477, 2.301, -0.235]} rotation={[Math.PI, 0, Math.PI]} scale={[0.909, 1, 1]} />
      <mesh geometry={nodes.Blind_45cm003.geometry} material={materials['Light Grey Matte Plastic']} position={[3.635, 2.299, -0.216]} rotation={[Math.PI, 0, Math.PI]} scale={[0.909, 0.907, 1]} />
      <group position={[-0.259, 3, 1.509]}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Light_Black Metal']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials.Light_Reflective} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials.Mat_Luce_LED} />
        <mesh geometry={nodes.Circle001_3.geometry} material={materials['Light Glass']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Alu._Powder_Coat.001']} position={[9.261, -0.449, 3.68]} scale={[1.316, 1.32, 1.316]} />
      <mesh geometry={nodes['2floor005'].geometry} material={materials.mRoof} position={[-0.399, -0.45, -0.288]} />
      <mesh geometry={nodes.Finestra_4.geometry} material={materials.Glass} position={[-0.399, -0.45, -0.288]} />
    </group>
  )
}

useGLTF.preload('/Ambiente-transformed.glb')
