/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Villa_Test_React.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.STRUTTURA.geometry}
        material={materials.color_cad1ee}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TELAIO002.geometry}
        material={materials['color_cad1ee.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.RIV_NOB_SP8_RIV_NOB_SP8_RI_NOB_SP8_X_P1A_SMART_PLUS_SM_DX_2400_X_1000_1_1_1.geometry
        }
        material={materials['color_cad1ee.003']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ANELLO_E795_HOPPE.geometry}
        material={materials['color_cad1ee.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Core_pannello_esterno.geometry}
        material={materials['color_cad1ee.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Overlay_pannello_esterno.geometry}
        material={materials['color_cad1ee.005']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PAVIMENTO_ESTERNO.geometry}
        material={materials.Stone}
      />
      <mesh castShadow receiveShadow geometry={nodes.Villa.geometry} material={materials.Plaster} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fences.geometry}
        material={materials['Oak raw fine wood texture.001']}
        position={[-0.183, 1.375, -0.697]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <group position={[-0.574, 1.85, 0.159]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1.geometry}
          material={materials.lamp_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1_1.geometry}
          material={materials['AR3DMat PBR Light Warm White']}
        />
      </group>
      <group position={[1.573, 1.85, 0.159]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1.geometry}
          material={materials.lamp_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_1_1.geometry}
          material={materials['AR3DMat PBR Light Warm White']}
        />
      </group>
      <group position={[-3.087, 4.868, 0.858]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['Alu. Powder Coat.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials[' Gasket Rubber.001']}
        />
      </group>
      <group position={[-2.315, 1.211, -0.014]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane809.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane809_1.geometry}
          material={materials['Alu. Powder Coat']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane809_2.geometry}
          material={materials[' Gasket Rubber']}
        />
      </group>
      <group position={[-0.796, 4.868, 0.858]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['Alu. Powder Coat.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials[' Gasket Rubber.001']}
        />
      </group>
      <group position={[1.494, 4.868, 0.858]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['Alu. Powder Coat.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials[' Gasket Rubber.001']}
        />
      </group>
      <group position={[3.785, 4.868, 0.858]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['Alu. Powder Coat.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials[' Gasket Rubber.001']}
        />
      </group>
      <group position={[-1.354, 0, 3.653]} rotation={[-Math.PI, 1.225, -Math.PI]} scale={0.922}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree002_1.geometry}
          material={materials['pine procedural.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree002_2.geometry}
          material={materials['Material.005']}
        />
      </group>
      <group position={[3.826, -0.041, 3.341]} scale={1.268}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fern.geometry}
          material={materials.fern}
          position={[-0.067, 0.003, 0]}
          rotation={[-Math.PI, 0.019, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fern001.geometry}
          material={materials.fern}
          position={[0.121, 0.003, 0.229]}
          rotation={[-Math.PI, 0.961, -Math.PI]}
          scale={0.577}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fern002.geometry}
          material={materials.fern}
          position={[-5.007, 0.003, -1.483]}
          rotation={[0, 0.637, 0]}
          scale={1.179}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fern003.geometry}
          material={materials.fern}
          position={[-4.862, 0.003, -1.221]}
          rotation={[0, -0.31, 0]}
          scale={0.497}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fern004.geometry}
          material={materials.fern}
          position={[-5.293, 0.003, -1.497]}
          rotation={[0, -1.148, 0]}
          scale={0.381}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Grass.001']}
        position={[0, -0.038, 0]}
      />
      <group position={[-4.377, -0.041, 3.031]} scale={0.801}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alexandra_Palm_1a038.geometry}
          material={materials.AlexandraPalm}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alexandra_Palm_1a038_1.geometry}
          material={materials['Wild Bush_Leaf.038']}
        />
      </group>
      <group position={[-4.071, -0.041, 3.408]} rotation={[Math.PI, -0.483, Math.PI]} scale={0.354}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alexandra_Palm_1a038.geometry}
          material={materials.AlexandraPalm}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alexandra_Palm_1a038_1.geometry}
          material={materials['Wild Bush_Leaf.038']}
        />
      </group>
      <group position={[-4.86, -0.041, 3.423]} rotation={[0, -1.378, 0]} scale={0.446}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alexandra_Palm_1a038.geometry}
          material={materials.AlexandraPalm}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Alexandra_Palm_1a038_1.geometry}
          material={materials['Wild Bush_Leaf.038']}
        />
      </group>
      <group position={[-0.576, -0.041, 0.358]} rotation={[-2.56, 1.208, 2.755]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree005.geometry}
          material={materials['Old brown wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree005_1.geometry}
          material={materials['phlox leaf']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree005_2.geometry}
          material={materials['phlox flower']}
        />
      </group>
      <group position={[1.575, -0.041, 0.329]} rotation={[-2.408, 1.276, 2.594]} scale={0.966}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree005.geometry}
          material={materials['Old brown wood']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree005_1.geometry}
          material={materials['phlox leaf']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Tree005_2.geometry}
          material={materials['phlox flower']}
        />
      </group>
      <group position={[-9.914, 0.6, 4.709]} scale={0.509}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[-9.922, 0.6, 1.131]} rotation={[0, -0.772, 0]} scale={0.57}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[-9.758, 0.6, -2.593]} rotation={[0, -1.289, 0]} scale={0.518}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[-9.914, 0.6, -6.37]} rotation={[0, -1.201, 0]} scale={0.59}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[-9.758, 0.6, -9.906]} rotation={[0, -1.289, 0]} scale={0.518}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[9.295, 0.6, -9.061]} rotation={[Math.PI, 0, Math.PI]} scale={0.564}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[9.56, 0.6, -5.737]} rotation={[-Math.PI, 0.772, -Math.PI]} scale={0.57}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[9.139, 0.6, -2.229]} rotation={[-Math.PI, 1.289, -Math.PI]} scale={0.518}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[9.295, 0.6, 1.233]} rotation={[-Math.PI, 1.201, -Math.PI]} scale={0.509}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[9.139, 0.6, 4.838]} rotation={[-Math.PI, 1.289, -Math.PI]} scale={0.518}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[7.981, 1.142, 13.243]} rotation={[Math.PI, -0.282, Math.PI]} scale={0.368}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[0.722, 0.446, 12.13]} rotation={[0, -1.201, 0]} scale={0.32}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[10.15, -0.044, 13.354]} rotation={[0, -1.201, 0]} scale={0.367}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group
        position={[2.568, 0.046, 12.204]}
        rotation={[0, -1.201, 0]}
        scale={[0.35, 0.309, 0.524]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[-0.753, 0.929, 11.82]} rotation={[0, -1.201, 0]} scale={0.32}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group
        position={[12.359, -0.32, 14.001]}
        rotation={[0, -1.201, 0]}
        scale={[0.46, 0.401, 0.709]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3.geometry}
          material={materials['Pine_Bark.005']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_short_3_1.geometry}
          material={materials['Evergreen_Leaf_1.005']}
        />
      </group>
      <group position={[-10.981, -0.646, -1.217]} scale={0.252}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group position={[-12.038, -0.646, 3.048]} rotation={[0, -0.398, 0]} scale={0.184}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group position={[-11.838, -0.646, -4.397]} rotation={[0, -0.87, 0]} scale={0.2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group position={[-12.033, -0.646, -8.206]} rotation={[0, -1.301, 0]} scale={0.221}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group position={[11.129, -0.646, -3.873]} rotation={[Math.PI, 0, Math.PI]} scale={0.24}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group position={[11.39, -0.646, -7.7]} rotation={[-Math.PI, 0.398, -Math.PI]} scale={0.203}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group
        position={[10.648, -0.646, -0.445]}
        rotation={[-Math.PI, 0.87, -Math.PI]}
        scale={0.257}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group
        position={[10.304, -0.646, 2.811]}
        rotation={[-Math.PI, 1.301, -Math.PI]}
        scale={0.221}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group position={[7.166, -0.237, 14.142]} rotation={[Math.PI, -0.27, Math.PI]} scale={0.114}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group
        position={[3.91, -0.174, 12.107]}
        rotation={[0, -1.301, 0]}
        scale={[0.116, 0.166, 0.099]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group position={[-1.334, 0.534, 13.023]} rotation={[Math.PI, -0.27, Math.PI]} scale={0.155}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2.geometry}
          material={materials['Twisted_Oak_Bark.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.evergreen_douglasfir_2_1.geometry}
          material={materials['Evergreen_Leaf_1.007']}
        />
      </group>
      <group position={[3.2, -0.041, 1.942]} rotation={[0, 0.415, 0]} scale={1.488}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree003.geometry}
          material={materials['pine procedural.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tree003_1.geometry}
          material={materials['Material.006']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rod001.geometry}
        material={materials['rod.002']}
        position={[0.36, 6.385, 0.673]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rod002.geometry}
        material={materials['rod.002']}
        position={[-2.324, 2.524, -0.249]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sheer.geometry}
        material={materials['white curtain.002']}
        position={[-2.565, 1.246, -0.366]}
        scale={[0.61, 0.817, 0.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.curtain.geometry}
        material={materials['curtain grey.002']}
        position={[-1.93, 1.248, -0.234]}
        scale={[0.527, 0.817, 0.82]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_Left.geometry}
        material={materials['Fabric Smooth Gray']}
        position={[-1.683, 5.525, 0.73]}
        rotation={[0, 0.029, 0]}
        scale={[1.305, 1.037, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_Left001.geometry}
        material={materials['Fabric Smooth Gray']}
        position={[-3.417, 5.525, 0.73]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1, 1.037, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_Left002.geometry}
        material={materials['Fabric Smooth Gray']}
        position={[0.296, 5.525, 0.73]}
        rotation={[Math.PI, -0.029, Math.PI]}
        scale={[1.326, 1.037, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_Left003.geometry}
        material={materials['Fabric Smooth Gray']}
        position={[3.795, 5.525, 0.73]}
        rotation={[Math.PI, -0.008, Math.PI]}
        scale={[1.305, 1.037, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curtain_Left004.geometry}
        material={materials['Fabric Smooth Gray']}
        position={[2.061, 5.525, 0.73]}
        rotation={[Math.PI, -0.036, Math.PI]}
        scale={[1, 1.037, 1]}
      />
    </group>
  )
}

useGLTF.preload('/Villa_Test_React.glb')