/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Villa_Test_React.glb --shadows --transform 
*/

import React, { useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model({ isNightMode, ...props }) {
  const { nodes, materials } = useGLTF('/Villa_Test_React-transformed.glb')

  useEffect(() => {
    // Non ci fidiamo più del materiale compresso per fare luce, 
    // lo spegniamo del tutto e usiamo il nostro trucco!
    if (materials.PaletteMaterial002) {
      materials.PaletteMaterial002.emissive.set('#000000');
      materials.PaletteMaterial002.emissiveIntensity = 0;
      materials.PaletteMaterial002.needsUpdate = true;
    }
  }, [materials, isNightMode]);

  return (
    <group {...props} dispose={null}>
      
      {/* --- GEOMETRIE COMPRESSE DELLA VILLA --- */}
      <group position={[2.172, -0.046, 3.072]} rotation={[0, 1.275, 0]} scale={0.955}>
        <mesh castShadow receiveShadow geometry={nodes.tree003.geometry} material={materials['pine procedural.002']} />
        <mesh castShadow receiveShadow geometry={nodes.tree003_1.geometry} material={materials['Material.006']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Prato.geometry} material={materials['Grass.001']} position={[0, -0.448, 0]} scale={10.667} />
      <mesh castShadow receiveShadow geometry={nodes.Aiutola.geometry} material={materials.mStone} position={[4.188, -0.225, 3.312]} />
      <mesh castShadow receiveShadow geometry={nodes.Terreno.geometry} material={materials['Dirt Ground']} position={[3.764, -0.046, 2.157]} />
      <group position={[-8.684, -0.449, 4.153]} scale={0.396}>
        <mesh castShadow receiveShadow geometry={nodes.evergreen_short_3004.geometry} material={materials['Pine_Bark.001']} />
        <mesh castShadow receiveShadow geometry={nodes.evergreen_short_3004_1.geometry} material={materials['Evergreen_Leaf_1.001']} />
      </group>
      <mesh castShadow receiveShadow geometry={nodes.Curve.geometry} material={materials.PaletteMaterial001} position={[1.298, 1.945, 0.085]} rotation={[Math.PI / 2, 0, 0]} scale={1.438} />
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.mPlaster} position={[-10.209, 0.85, -0.837]} scale={[0.603, 1, 1]} />
      
      {/* STRUTTURA DEL FARETTO A SOFFITTO (Il modello in metallo) */}
      <group position={[-0.259, 3, 1.509]}>
        <mesh castShadow receiveShadow geometry={nodes.Circle001.geometry} material={materials['Light_Black Metal']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      
      <mesh castShadow receiveShadow geometry={nodes.Blind_45cm003.geometry} material={materials['Light Grey Matte Plastic']} position={[3.635, 2.299, -0.216]} rotation={[Math.PI, 0, Math.PI]} scale={[0.909, 0.907, 1]} />
      <mesh castShadow receiveShadow geometry={nodes.Plane002.geometry} material={materials.PaletteMaterial003} position={[1.302, 1.269, 0.123]} rotation={[Math.PI / 2, 0, 0]} scale={0.892} />
      <mesh castShadow receiveShadow geometry={nodes['1floor003'].geometry} material={materials.mRoof} position={[-0.399, -0.45, -0.288]} />
      <mesh castShadow receiveShadow geometry={nodes.window.geometry} material={materials.Glass} position={[-0.399, -0.45, -0.288]} />
      <mesh castShadow receiveShadow geometry={nodes.woodPlanks002.geometry} material={materials.mWood} position={[-0.399, -0.45, -0.288]} />

      {/* --- LE LUCI REALI E VISIBILI (Notte) --- */}
      {isNightMode && (
        <group name="Luci-Reali-Notturne">
          
          {/* =========================================
              LA "FINTA" LAMPADINA (Infallibile)
              ========================================= */}
          <mesh position={[-0.259, 3, 1.509]}>
            {/* Creiamo una piccolissima sfera di 4 centimetri */}
            <sphereGeometry args={[0.04, 16, 16]} />
            {/* MeshBasicMaterial ignora le ombre ed è luminoso di natura. toneMapped={false} lo fa brillare. */}
            <meshBasicMaterial color="#fff1d8" toneMapped={false} />
          </mesh>

          {/* =========================================
              LA LUCE PROIETTATA (Il fascio reale)
              ========================================= */}
          {/* L'ho abbassata a Y=2.70 come test per farti vedere la differenza dall'origine */}
          <spotLight 
            position={[-0.259, 2.70, 1.509]} 
            intensity={10} 
            distance={8} 
            angle={0.65} 
            penumbra={0.7} 
            decay={2} 
            color="#fff1d8" 
            castShadow
            shadow-mapSize={[2048, 2048]} 
            shadow-bias={-0.0001}
            shadow-normalBias={0.02}
          >
            <object3D attach="target" position={[-0.259, 0, 1.509]} />
          </spotLight>

        </group>
      )}

    </group>
  )
}

useGLTF.preload('/Villa_Test_React-transformed.glb')